### ISSUE TITLE
maximum path sum in binary tree

### ISSUE THREAD

**Issue by sona-123** [dharmanshu9930/Daa-#84]
want to add the code for maximum sum in binary tree

**Comment by Soumili1818** [comment]
Yes please,kindly assign me

**Comment by AkanshuAich** [comment]
Plz let me to resolve the issue want to add the code for the following task

**Comment by dharmanshu9930** [comment]
@Soumili1818 @AkanshuAich Please write the code for finding maximum sum in binary tree and send me the pull request
